
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectIPDialog.java
 *
 * Created on 9 May, 2011, 4:27:36 PM
 */

/**
 *
 * @author Rajus
 */
public class SelectIPDialog extends javax.swing.JDialog {

    /** Creates new form SelectIPDialog */
    public SelectIPDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Details of Selected IP");
        startMethod();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectedIPLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PacketInfoTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        PacketDataTextArea = new javax.swing.JTextArea();
        IPLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SelectedIPLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectedIPLabel.setForeground(new java.awt.Color(102, 102, 255));
        SelectedIPLabel.setText("Selected IP :");

        PacketInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time ", "Source IP", "Destination IP", "Length", "Protocol", "Data Length", "Time Stamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PacketInfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacketInfoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PacketInfoTable);

        PacketDataTextArea.setColumns(20);
        PacketDataTextArea.setRows(5);
        jScrollPane3.setViewportView(PacketDataTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SelectedIPLabel)
                        .addGap(16, 16, 16)
                        .addComponent(IPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectedIPLabel)
                    .addComponent(IPLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PacketInfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PacketInfoTableMouseClicked
        // TODO add your handling code here:

        int selectedrowindex=PacketInfoTable.getSelectedRow();

        long selectedTimeStamp=Long.parseLong((String)PacketInfoTable.getValueAt(selectedrowindex,6));
        System.out.println("Selected row index:"+selectedrowindex+"select time stamp:"+selectedTimeStamp);
        FileHandler file=new FileHandler();
        String returndata = file.fileReader(String.valueOf(selectedTimeStamp));
        try {
           // ResultSet PacketData = MainThread.stmt.executeQuery("select * from PacketInfo where time_stamp=" + selectedTimeStamp);
          // if( PacketData.next())
            PacketDataTextArea.setText(returndata);
        } catch (Exception ex) {
            System.out.println("Retrieve Error: SQL "+ex);

            //Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PacketInfoTableMouseClicked

    /**
    * @param args the command line arguments
    */
    public void startMethod() {
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectIPDialog dialog = new SelectIPDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });*/
                this.setVisible(true);
            
        //});
    }
    public void setLabel(String ip){
        IPLabel.setText(ip);
    }
    public void addInfoPacketInfoTable(String []data) {

        DefaultTableModel dtm=(DefaultTableModel)PacketInfoTable.getModel();
        dtm.addRow(data);


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IPLabel;
    private javax.swing.JTextArea PacketDataTextArea;
    private javax.swing.JTable PacketInfoTable;
    private javax.swing.JLabel SelectedIPLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
